<?php

/**
 * @file
 * z_menu_permissions.module
 * Boutros AbiChedid. boutrosa@princeton.edu - Start date May 12, 2014.
 * BAC. Edit date: July 31, 2015
 * A module that overrides Drupal permission system.
 * 'z' is to make sure that my module executes after the menu module.
 * Drupal executes modules in alphabetical order or if priorities are specifically set.
 */

/**
 * Implements hook_permission().
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_permission/7
 */
function z_menu_permissions_permission() {
  return array(
    'add menu items' => array(
      'title' => t('Add Menu Items'),
      'description' => t('Allows users to add Menu items from the Node form and Allows users to directly add Links to the Menu.'),
    ),
  );
}

/**
 * https://api.drupal.org/api/drupal/modules!menu!menu.module/function/menu_form_node_form_alter/7
 * Allows administrators to customize the site's navigation menus.
 */
function z_menu_permissions_form_node_form_alter(&$form, $form_state) {
  if (isset($form['menu'])) {
    $form['menu']['#access'] = user_access('add menu items') || user_access('administer menu');
  }
}

/**
 * Implements hook_menu_alter().
 */
function z_menu_permissions_menu_alter(&$items) {
	 $items['admin/structure/menu/manage/%menu/add']['access callback'] = 'z_menu_permissions_add_menu_link';
}

/**
 * Allows Content Editors to directly add links to the Menu.
 */
function z_menu_permissions_add_menu_link() {
  return (user_access('add menu items')|| user_access('administer menu'));
}